### ISSUE TITLE
Create B2B Connector Reference page

### ISSUE THREAD

**Issue by IanWhyte** [modusintegration/mulesoft-docs#2]
(1) Create a reference page for the B2B connector, including installation instructions, along the lines of the existing X12 page (https://developer.mulesoft.com/docs/display/current/X12+Module).
(2) Assign issue to Ian for edit.

**Comment by claudemamo** [comment]
This is done: https://github.com/modusintegration/mulesoft-docs/blob/master/anypoint-b2b/v/latest/partner-manager-connector.adoc
