### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by IanWhyte** [modusintegration/mulesoft-docs#3]
This is a test to see whether or not, and how, an assignee gets notification of an issue.
Kent, can you reply here so I can see how this works?

**Comment by kentbrownalpha** [comment]
Yep, I got it.

On Wed, Oct 7, 2015 at 11:46 AM, IanWhyte <notifications@github.com> wrote:

> Assigned #3 <https://github.com/modusintegration/mulesoft-docs/issues/3>
> to @kentbrownalpha <https://github.com/kentbrownalpha>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modusintegration/mulesoft-docs/issues/3#event-429480972>
> .
>



-- 
[image: www.modusbox.com] <http://www.modusbox.com/>


*Kent Brown,* CTO 411 1st Ave. South, Suite 502, Seattle, WA
 425.677.5241 | kent@modusbox.com

*2015 MuleSoft Delivery Partner of the Year*

**Comment by IanWhyte** [comment]
Closing the test
